// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContactUpdateRequest.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TeamNote.Protocol {

  /// <summary>Holder for reflection information generated from ContactUpdateRequest.proto</summary>
  public static partial class ContactUpdateRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for ContactUpdateRequest.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ContactUpdateRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpDb250YWN0VXBkYXRlUmVxdWVzdC5wcm90byInChRDb250YWN0VXBkYXRl",
            "UmVxdWVzdBIPCgdDbGllbnRzGAEgAygDQhZIAaoCEVRlYW1Ob3RlLlByb3Rv",
            "Y29sYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TeamNote.Protocol.ContactUpdateRequest), global::TeamNote.Protocol.ContactUpdateRequest.Parser, new[]{ "Clients" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ContactUpdateRequest : pb::IMessage<ContactUpdateRequest> {
    private static readonly pb::MessageParser<ContactUpdateRequest> _parser = new pb::MessageParser<ContactUpdateRequest>(() => new ContactUpdateRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ContactUpdateRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TeamNote.Protocol.ContactUpdateRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContactUpdateRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContactUpdateRequest(ContactUpdateRequest other) : this() {
      clients_ = other.clients_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContactUpdateRequest Clone() {
      return new ContactUpdateRequest(this);
    }

    /// <summary>Field number for the "Clients" field.</summary>
    public const int ClientsFieldNumber = 1;
    private static readonly pb::FieldCodec<long> _repeated_clients_codec
        = pb::FieldCodec.ForInt64(10);
    private readonly pbc::RepeatedField<long> clients_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<long> Clients {
      get { return clients_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ContactUpdateRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ContactUpdateRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!clients_.Equals(other.clients_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= clients_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      clients_.WriteTo(output, _repeated_clients_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += clients_.CalculateSize(_repeated_clients_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ContactUpdateRequest other) {
      if (other == null) {
        return;
      }
      clients_.Add(other.clients_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10:
          case 8: {
            clients_.AddEntriesFrom(input, _repeated_clients_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
